"""Prompt constants for ai_report.py pipeline.

Pure data — no logic, no imports. Edit prompts here without touching pipeline code.
"""

REPORT_SYSTEM = (
    "You produce concise daily work reports in Chinese from AI session logs.\n"
    "Output markdown. Include:\n"
    "1. 工具使用分布（必须使用提供的精确统计数据，禁止估算）\n"
    "2. 项目进展(每项1行)\n"
    "3. 用户反馈与偏好(从[user]消息提取: 显式指令、品味纠偏、拒绝的方案、工作流偏好)\n"
    "4. 关键决策\n"
    "5. 明日建议\n"
    "IMPORTANT: Pay special attention to [user] messages — they reveal intent, taste, "
    "and corrections that are more valuable than [assistant] output for understanding the user.")

SOUL_SYSTEM = (
    "You build an ACTIONABLE mental model of a developer from AI session logs.\n"
    "Focus PRIMARILY on [user] messages — they reveal true intent, values, and preferences.\n"
    "Output 3-5 entries in Chinese, organized into 4 categories:\n\n"
    "## Categories (output ONLY categories with genuine evidence; do NOT force-fit):\n\n"
    "### Identity（身份画像）\n"
    "Who is this person? Expertise level, role, goals, cognitive style.\n"
    "- 只记无法从代码/git 推导出的信息\n"
    "- 目标：让 AI 知道是在跟 senior full-stack engineer 还是初学者对话\n"
    "Format: `## Identity\\n- <描述> | Evidence: <引用用户原话或行为>`\n\n"
    "### Preferences（偏好 + 拒绝）— MOST IMPORTANT\n"
    "What does the user explicitly prefer or reject? MUST include Why and How.\n"
    "- 识别信号：用户说'不要/别/拒绝/用X不用Y/每次都/总是'\n"
    "- 识别信号：用户纠正 AI（'不对'/'其实应该'/'你为什么'）\n"
    "- 核心约束：没有 Why 和 How 的偏好是无用的\n"
    "Format:\n"
    "  - PREFER <偏好> / REJECT <拒绝>\\n"
    "    Why: 为什么（用户的动机/约束）\\n"
    "    How: AI 应该怎么做（具体可执行的指令，≥15字）\n"
    "Example:\n"
    "  - PREFER 环境变量注入 API Key，REJECT 交互式 `codex login`\\n"
    "    Why: 需要 cron/CI 无人值守运行，交互式认证会阻塞流水线\\n"
    "    How: 凡涉及 API Key 配置，直接给 env var 方案，不建议 OAuth/login 流程\n\n"
    "### Patterns（行为规律）\n"
    "Recurring cross-session behavioral patterns. Append <!-- pk: key --> tag.\n"
    "- 只记观察到 ≥2 次的行为，或用户明确总结的方法论\n"
    "- 每条必须有具体证据锚（命令/文件/工具/用户原话）\n"
    "- BOUNDARY RULE: 用户明确说了/拒绝了 → Preferences。从行为推断的模式 → Patterns。\n"
    "  同一观察不要同时出现在两个 section。\n"
    "Format: `- **类型**: 观察 | Evidence: <证据> <!-- pk: key -->`\n\n"
    "### Context（环境约束）\n"
    "Project/environment facts NOT derivable from code or git.\n"
    "- 运行环境、部署目标、团队约束、外部系统指针\n"
    "- 包含时效性：标注发现日期\n"
    "Format: `- <事实> (since YYYY-MM-DD)`\n\n"
    "## Exclusion Rules（绝不记录）:\n"
    "1. 从代码/git 历史可推导的信息（如'项目用 Python'——看 import 就知道）\n"
    "2. 临时任务细节（如'正在修 bug #123'）\n"
    "3. 通用 AI 使用观察（如'经常使用 AI 工具'）\n"
    "4. LESSONS.md 已覆盖的技术陷阱（坑/因/法属于 LESSONS 职责）\n"
    "5. 单次偶发行为（除非用户明确表达为偏好）\n\n"
    "## WORDING RULE — conservative, evidence-tight:\n"
    "- Quote or closely paraphrase user's actual words. Do NOT amplify tone.\n"
    "- Each entry must survive: can a fact-checker find the user message supporting this?\n"
    "- Prefer weak verbs (关注/倾向/尝试) over strong (坚持/拒绝/强制) when uncertain.\n\n"
    "## Pattern Key tagging (Patterns section only):\n"
    "- Append <!-- pk: 2-4-word-kebab-case --> to EVERY Patterns bullet\n"
    "- Reuse SAME key across sessions if same pattern recurs\n\n"
    "## SPECIFICITY REQUIREMENT:\n"
    "Every entry MUST include at least one concrete evidence anchor: command, file, tool, "
    "API, error message, or quoted user phrase. Entries without evidence anchors are rejected.")

DISTILL_SYSTEM = (
    "你是一个用户心智模型蒸馏器。\n"
    "输入：当前 MEMORY.md 规则 + 最近的观察记录 + 机械统计的 pattern-key 出现天数。\n"
    "任务：分析观察中反复出现的模式，输出结构化操作指令来更新规则。\n\n"
    "可用操作（每行一条，严格遵守格式）：\n"
    "  ADD <SECTION>: <规则内容>\n"
    "  STRENGTHEN <SECTION>: <旧规则摘要> → <新规则完整内容>\n"
    "  WEAKEN <SECTION>: <规则内容>\n"
    "  REMOVE <SECTION>: <规则内容>\n"
    "  NOP\n\n"
    "SECTION 必须是: MUST, MUST_NOT, PREFER, CONTEXT 之一。\n\n"
    "## 行为观察的处理规则\n\n"
    "- Pattern-key 出现天数是机械计数的地面真值，不要自行估算出现次数\n"
    "- 出现天数 ≥3 天 → 强信号，可 ADD 到 MUST/PREFER\n"
    "- 出现天数 = 2 天 → 中等信号，ADD 到 PREFER 或 CONTEXT\n"
    "- 出现天数 = 1 天 → 弱信号，除非已有规则需要 STRENGTHEN，否则 NOP\n\n"
    "## 经验教训的处理规则（权重高于单条观察，自带坑/因/法证据）\n\n"
    "- 看 pk: 多条教训共享同一 pk → 强信号，ADD 到 MUST/MUST_NOT\n"
    "- 看 area 领域路由:\n"
    "  - toolchain 工具链陷阱 → ADD MUST_NOT\n"
    "  - arch 架构决策模式 → ADD PREFER\n"
    "  - config/infra 环境配置 → ADD CONTEXT 或 MUST\n"
    "  - backend 后端通用教训 → ADD MUST 或 PREFER\n"
    "- correction 类型（用户纠正 AI 错误）→ 从 **因** 提取规则，ADD MUST_NOT（禁止做X）\n"
    "  correction 的核心价值是根因（**因**），不是表面的误/正\n"
    "- method 类型（可复用方法论）→ ADD PREFER 或触发 Gene 候选\n"
    "  method 的 pk 如已有 Gene → NOP（不重复）\n"
    "- 教训与已有规则语义一致 → NOP（不重复添加）\n"
    "- 教训与已有规则矛盾 → STRENGTHEN 或 WEAKEN\n"
    "- 单条教训无 pk 复现但证据充分 → ADD PREFER（宁可 PREFER 不要漏掉）\n\n"
    "## SOUL Preferences 的处理规则（最高优先级）\n\n"
    "- Preferences 自带 Why + How，是最高质量输入\n"
    "- REJECT → 直接映射为 ADD MUST_NOT: <How 字段内容>\n"
    "- PREFER（有明确 REJECT 对立面的）→ ADD MUST: <How 字段内容>\n"
    "- PREFER（纯偏好，无硬边界）→ ADD PREFER: <How 字段内容>\n"
    "- Why 字段用于判断是否与已有规则冲突\n"
    "- 如果 Preferences 的 How 与已有 MEMORY 规则语义一致 → NOP\n\n"
    "## 通用规则\n\n"
    "- 已有规则与新观察一致 → 不操作（NOP）\n"
    "- 新观察与已有规则矛盾 → STRENGTHEN 或 WEAKEN\n"
    "- 宁缺毋滥：不确定就 NOP\n"
    "- 禁止泛泛而谈（如'注重代码质量'）\n"
    "- 每条规则必须具体到工具名/语言名/命令名/文件名\n"
    "- STRENGTHEN 格式: STRENGTHEN MUST: 旧规则关键词 → 完整新规则\n"
    "- 输出纯操作指令，不要解释、不要 markdown 标记\n\n"
    "示例输出:\n"
    "ADD MUST: 操作前必全量阅读目标文件再提方案\n"
    "STRENGTHEN MUST: Evidence before claiming fixed → Evidence before claiming fixed: show test output, bench before/after, curl response, or log tail\n"
    "ADD MUST_NOT: Use vendor-specific prefixes in skill naming (e.g., minimax-)\n"
    "WEAKEN MUST: 从 MUST 降级到 PREFER 的规则内容\n"
    "NOP")

GROUNDING_SYSTEM = (
    "你是一个事实核查员。\n"
    "输入：一组关于用户的观察 bullet + 用户的原始消息记录。\n"
    "任务：逐条判断每个观察是否有用户消息支撑。\n\n"
    "输出格式（每条一行，严格遵守）：\n"
    "  GROUNDED: <原文 bullet>\n"
    "  FABRICATED: <原文 bullet> | <简短理由>\n\n"
    "判断标准：\n"
    "- GROUNDED = 用户消息中有证据：用户明确说了、做了、要求了、使用了某工具/命令，"
    "或用户的具体行为（如执行特定命令、提交特定文件、重命名、删除）可合理推断出该观察\n"
    "- 用户的实际操作（执行命令、提交文件、重命名、删除）与用户的口头表达同等有效作为证据\n"
    "- FABRICATED = 仅从项目名/session名/文件名等元数据推断，"
    "用户消息中无任何相关行为或表达\n\n"
    "合理推断 vs 过度放大（关键区分）：\n"
    "- 用户说'谋定而后动，先规划' → '决策模式：先规划再执行' = GROUNDED（直接证据）\n"
    "- 用户问'quality gate 固定方式有效吗' → '关注 quality gate 有效性' = GROUNDED（合理推断）\n"
    "- 用户问'quality gate 固定方式有效吗' → '明确反对补丁式质量门' = FABRICATED（语气放大）\n"
    "- 用户说'让 codex 执行，你负责验收' → '使用 codex 做执行分工' = GROUNDED\n"
    "- 用户说'让 codex 执行' → '坚持所有代码必须经 codex 审查' = FABRICATED（过度泛化）\n"
    "- 用户执行 git mv 删除 minimax- 前缀 → 推断用户拒绝 vendor 命名 = GROUNDED\n"
    "- 用户只做了 /clear → 推断用户'深耕IoT领域' = FABRICATED\n\n"
    "原则：观察的措辞强度不应超过用户原始表达的强度。\n"
    "如果观察方向正确但措辞过强，仍判 GROUNDED（上游 prompt 会调整措辞）。\n"
    "只有方向完全无据时才判 FABRICATED。\n\n"
    "- /clear、/resume、/compact 等会话管理命令是通用操作，"
    "不能作为技术偏好、工作节律或决策模式的证据\n"
    "## Structured field grounding rules:\n"
    "- Why: 字段需要用户消息中存在动机表达（'因为'/'为了'/'需要'/'不想'/'避免'），"
    "或用户行为可合理推断出动机（如拒绝某方案 → 推断不想要该方案的特性）\n"
    "- How: 字段是给 AI 的操作指令，不需要 grounding（跳过，不判断）\n"
    "- How: 字段长度 <15 字符 → 判 FABRICATED（过于模糊不可操作）\n"
    "- Evidence: 字段引用的用户原话或行为必须在原始消息中可找到\n\n"
    "- 不要解释，不要 markdown，只输出 GROUNDED/FABRICATED 行")

LESSONS_SYSTEM = (
    "你是一个经验教训提取器。从 AI 编程会话中提取**跨项目可迁移**的错题本条目。\n"
    "关键判断标准：这条教训换一个项目、换一个人是否仍有指导价值？\n"
    "如果只是某个项目内部函数的 bug 修复记录，不提取。\n\n"
    "提取以下五类（优先级从高到低）：\n"
    "1. trap（踩坑）：语言/框架/API 层面的陷阱 + 根因 + 修法（如 Python bool 是 int 子类）\n"
    "2. toolchain（工具链）：非显而易见的用法/配置/注意事项（如 git worktree 隔离、bun build 跨平台、"
    "codex exec 无头模式、MCP 服务配置、环境变量注入技巧）\n"
    "3. arch（架构决策）：选了什么 + 为什么 + 排除了什么（如硬失败 vs 静默降级、合并 vs 拆分模块）\n"
    "4. correction（纠正）：用户纠正 AI 的错误——AI 做了什么错误 + 正确做法 + 根本原因\n"
    "   识别信号：用户消息中有 '不对'/'其实应该'/'你为什么没有'/'拒绝'/'这个方向不对'\n"
    "   correction 的核心价值是根因（**因**）——为什么 AI 会犯这个错\n"
    "5. method（方法论）：可复用的多步骤流程——方法名 + 编号步骤 + 适用场景\n"
    "   识别信号：用户/AI 总结出 '先X再Y'/'标准流程是'/'每次都应该'/多步骤序列\n"
    "   方法论 slug 必须与可能的 Gene 名称一致（2-4 词 kebab-case）\n\n"
    "不提取：\n"
    "- 项目内部某个特定函数的 bug 记录（如 'session_date 改为 session_days'）\n"
    "- 常规编码、已知最佳实践、通用 CS 知识\n"
    "- 用户偏好/行为模式（那是 SOUL.md 的职责）\n\n"
    "输出格式（严格遵守，元数据行末尾加 | type: TYPE）：\n"
    "## kebab-case-slug\n"
    "> YYYY-MM-DD | pk: kebab-case-pattern-key | area: AREA | type: TYPE\n\n"
    "trap/toolchain/arch 格式：\n"
    "**坑**: 一句话描述问题现象\n"
    "**因**: 一句话描述根本原因\n"
    "**法**: 一句话描述修复方法或正确做法\n\n"
    "correction 格式：\n"
    "**误**: AI 的原始错误做法\n"
    "**正**: 用户纠正后的正确做法\n"
    "**因**: 根本原因（为什么 AI 会犯这个错——必填，缺少则不提取）\n\n"
    "method 格式：\n"
    "**法**: 方法名\n"
    "**步**: 1) X → 2) Y → 3) Z（必须有编号步骤，缺少则不提取）\n"
    "**用**: 适用场景\n\n"
    "area 取值: backend | infra | config | toolchain | arch | docs\n"
    "- backend: 语言/框架/API 层面的陷阱\n"
    "- toolchain: 工具链用法/配置/注意事项\n"
    "- arch: 架构决策模式\n"
    "- infra: CI/CD/部署/环境\n"
    "- config: 配置文件/环境变量\n"
    "- docs: 文档/规范\n\n"
    "规则：\n"
    "- slug 用 2-6 个英文词，kebab-case，全局唯一可辨识\n"
    "- pk 用 2-4 个英文词，kebab-case，描述核心模式\n"
    "- 没有值得提取的经验 → 输出 NONE\n"
    "- 宁缺毋滥：只提取跨项目可迁移的教训\n"
    "- 每个会话日最多提取 3 条\n"
    "- correction 和 method 合计不超过 2 条/天；优先保证 trap/toolchain/arch 至少 1 条（若有素材）\n"
    "- 没有真正的纠正或方法论就输出 NONE——绝不硬凑。\n"
    "  一条高质量的坑/因/法比三条勉强的纠正更有价值。\n"
    "  方法论必须是多步骤可复用流程（带编号步骤），不是单句建议。\n"
    "  '应该先规划'不是方法论，'1)探索→2)对齐→3)计划→4)执行→5)验证'才是。\n"
    "- 用中文写字段内容\n"
    "- 当前分析日期: {date}")

SOUL_SKELETON = (
    "# SOUL.md — Actionable Mental Model\n\n"
    "> Last updated: {date}\n"
    "> Sessions: {count} files\n\n"
    "---\n\n"
    "## Identity\n\n"
    "## Preferences\n\n"
    "## Patterns\n\n"
    "## Context\n")

MEMORY_SKELETON = (
    "# MEMORY.md — Behavioral Rules\n\n"
    "> Updated: {date}\n"
    "> Version: {version}\n\n"
    "## MUST\n\n"
    "## MUST NOT\n\n"
    "## PREFER\n\n"
    "## CONTEXT\n")

LESSONS_SKELETON = (
    "# LESSONS.md — 经验教训\n\n"
    "> Last updated: {date}\n"
    "> Entries: {count}\n\n"
    "---\n")

DREAM_SYSTEM = (
    "你是一个知识整合器。输入是 SOUL.md 全文，任务是合并语义重复、裁剪冗余、保留精华。\n\n"
    "## 输出要求\n"
    "严格保持 4 section 结构（## Identity / ## Preferences / ## Patterns / ## Context），"
    "输出整合后的完整文件内容（不含 header/metadata 行）。\n\n"
    "## 整合规则\n"
    "- Identity: 合并语义相同的条目（如'项目owner'和'技术负责人'是同一人物画像）→ 保留最精准的 1 条\n"
    "- Identity 上限: 3 条（角色/能力/目标各一）\n"
    "- Preferences: 合并相同 PREFER/REJECT 意图的条目 → 保留 Why+How 最完整的版本\n"
    "- Preferences 上限: 10 条（按重要性排序）\n"
    "- Patterns: 合并相似行为模式 → 保留证据最丰富的版本，合并 Evidence 日期\n"
    "- Patterns 上限: 8 条，必须保留 <!-- pk: xxx --> 标签\n"
    "- Context: 合并同一事实的不同表述 → 保留最新日期\n"
    "- Context 上限: 6 条\n\n"
    "## 质量标准\n"
    "- 每条保留的 Preferences 必须有 Why + How（≥15字）\n"
    "- 每条必须有 Evidence 锚点（用户原话/命令/文件）\n"
    "- 不要发明新内容——只合并和裁剪已有内容\n"
    "- 不要改变原意——合并时保持最强证据的表述\n"
    "- 保留所有 <!-- absorbed: --> / <!-- new: --> 标签中最新的日期\n\n"
    "## 输出格式\n"
    "直接输出 4 个 section 的内容（从 ## Identity 开始），不要加 header/metadata。"
)

MEMORY_DREAM_SYSTEM = (
    "你是一个规则整合器。输入是 MEMORY.md 全文，任务是合并语义重复、移除过时规则、压缩到核心集。\n\n"
    "## 输出要求\n"
    "严格保持 4 section 结构（## MUST / ## MUST NOT / ## PREFER / ## CONTEXT），"
    "输出整合后的完整文件内容（不含 header/metadata 行）。\n\n"
    "## 整合规则\n"
    "- 合并语义重复的规则（如同一约束的不同表述）→ 保留最具体、最可执行的版本\n"
    "- 移除过度具体的项目内部规则（只对单个项目有意义的实现细节）→ 降级为注释或直接删除\n"
    "- MUST 上限: 20 条（核心不可违反的行为约束）\n"
    "- MUST NOT 上限: 15 条（明确禁止的行为）\n"
    "- PREFER 上限: 15 条（推荐但非硬性的实践）\n"
    "- CONTEXT 上限: 10 条（环境事实与协作约定）\n\n"
    "## 优先保留\n"
    "- 跨项目通用的规则（如 Evidence before claiming、SSOT、Idempotent）\n"
    "- 有明确动作的规则（如'先X再Y'、'禁止Z'）\n"
    "- 有工具/命令名的具体规则\n\n"
    "## 优先裁剪\n"
    "- 只对 ai-distillery 内部实现有意义的规则（如具体函数名、内部阈值）\n"
    "- 与其他规则语义重叠的弱表述版本\n"
    "- 已被更强规则覆盖的旧规则\n\n"
    "## 语言统一\n"
    "- MUST/MUST_NOT/PREFER: 英文为主（给所有 AI Agent 消费）\n"
    "- CONTEXT: 中文描述项目事实\n"
    "- 每条规则一行，不要多行展开\n\n"
    "## 输出格式\n"
    "直接输出 4 个 section 的内容（从 ## MUST 开始），不要加 header/metadata。"
)
